### ISSUE TITLE
Macro Error

### ISSUE THREAD

**Issue by sreyarahman** [savagedude3/Micro_Morph#2]
I've also gotten this macro error a few times when running micromorph.ijm and micromorph batch, which prevents the threshold setting window from coming up: 

![Screenshot (4)](https://user-images.githubusercontent.com/72880909/96020781-8816c980-0e1c-11eb-99c5-a9e904e356de.png)

**Comment by savagedude3** [comment]
This seems like an error with microMorph instead of microMorphBatch. Let me know if you get the same error with the Batc version, I made a lot of improvements to the batch version other than just being able to run on multiple images.
